version: '3.7'

services:
  granja:
    build: ./Granja
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Granja/:/usr/src/Granja/
    ports:
      - 52000:8000
    env_file:
      - ./.env.dev
    links: 
      - db:db
    depends_on:
      - db
  db:
    restart: always
    container_name: db
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
      
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.prod.pg
    ports:
      - "80:80"
    links: 
      - db:db
    depends_on:
      - db

volumes:
  postgres_data: